title: Salma Abdelhamid # your name (or website title) here
logo: "/Abdelhamid,Salma.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, and welcome to my portfolio! 
  <br><br>
  Thank you for your interest.
  <br><br>
  <a href="https://www.linkedin.com/in/salma-abdelhamid/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
